[package]
authors = ["Rowan Herbert <37909949+RLHerbert@users.noreply.github.com>"]
edition = "2018"
name = "fizz_buzz_functional_composition"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
